import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Space_Grotesk } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const spaceGrotesk = Space_Grotesk({
  // weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Purdue Hackers Wiki',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>{children}</body>
    </html>
  )
}
